version: '3.8'

services:
  backend:
    image: ${ECR_REGISTRY}/hanihome-au-backend:${IMAGE_TAG:-latest}
    container_name: hanihome-backend-staging
    environment:
      SPRING_PROFILES_ACTIVE: staging
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_ASSETS: ${AWS_S3_BUCKET_ASSETS}
      AWS_S3_BUCKET_BACKUPS: ${AWS_S3_BUCKET_BACKUPS}
      AWS_S3_BUCKET_LOGS: ${AWS_S3_BUCKET_LOGS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SENTRY_DSN: ${SENTRY_DSN}
      LOG_LEVEL: info
      ENABLE_SWAGGER: true
      ENABLE_ACTUATOR: true
    ports:
      - "8080:8080"
    networks:
      - hanihome-network
    restart: unless-stopped
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/hanihome-au-staging
        awslogs-region: ap-southeast-2
        awslogs-stream-prefix: backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    image: ${ECR_REGISTRY}/hanihome-au-frontend:${IMAGE_TAG:-latest}
    container_name: hanihome-frontend-staging
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://api.staging.hanihome.com.au/api/v1
      NEXT_PUBLIC_APP_NAME: HaniHome Australia (Staging)
      NEXT_PUBLIC_APP_URL: https://staging.hanihome.com.au
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      NEXT_PUBLIC_KAKAO_CLIENT_ID: ${NEXT_PUBLIC_KAKAO_CLIENT_ID}
      NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_STAGING_ID}
      NEXTAUTH_URL: https://staging.hanihome.com.au
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_JWT_SECRET: ${NEXTAUTH_JWT_SECRET}
      SENTRY_DSN: ${SENTRY_DSN}
      NEXT_PUBLIC_SENTRY_DSN: ${SENTRY_DSN}
      NEXT_PUBLIC_DEBUG_MODE: false
      NEXT_PUBLIC_ENABLE_ANALYTICS: true
      NEXT_PUBLIC_ENABLE_ERROR_TRACKING: true
    ports:
      - "3000:3000"
    networks:
      - hanihome-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/hanihome-au-staging
        awslogs-region: ap-southeast-2
        awslogs-stream-prefix: frontend

  redis:
    image: redis:7-alpine
    container_name: hanihome-redis-staging
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - hanihome-network
    volumes:
      - redis_data:/data
    restart: unless-stopped
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/hanihome-au-staging
        awslogs-region: ap-southeast-2
        awslogs-stream-prefix: redis
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: hanihome-nginx-staging
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/staging.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    networks:
      - hanihome-network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/hanihome-au-staging
        awslogs-region: ap-southeast-2
        awslogs-stream-prefix: nginx

volumes:
  redis_data:
    driver: local

networks:
  hanihome-network:
    driver: bridge